library(NHANES)
library(tidyverse)
data("NHANES")
glimpse(NHANES)
nrow(NHANES)
ncol(NHANES)
hist(NHANES$Age)
hist(NHANES$BMI)
hist(NHANES$BPSysAve)
hist(NHANES$Height)
hist(NHANES$Weight)
adults <- NHANES %>% filter(Age>=20)
hist(adults$Height)
mean(NHANES$Age, na.rm =TRUE); median(NHANES$Age, na.rm =TRUE )
mean(NHANES$BMI, na.rm =TRUE); median(NHANES$BMI, na.rm =TRUE )
mean(NHANES$BPSysAve, na.rm =TRUE); median(NHANES$BPSysAve, na.rm =TRUE )
mean(NHANES$Height, na.rm =TRUE); median(NHANES$Height, na.rm =TRUE )
mean(NHANES$Weight, na.rm =TRUE); median(NHANES$Weight, na.rm =TRUE )
mean(adults$Weight, na.rm=TRUE); median(adults$Weight, na.rm=TRUE)
mean(adults$Height, na.rm=TRUE); median(adults$Height, na.rm=TRUE)
